### PR TITLE
Fix crash in truncation

### LINKED ISSUE #40: crash on Truncation.swift:57 let originalLine = lines[originalIndex]
// numberOfLines = 0
// tokenLines.count = 1
// index = 0
// originalIndex = -1
Truncation.swift:49  let originalIndex = self.numberOfLines - tokenLines.count + index

crash on Truncation.swift:57 let originalLine = lines[originalIndex]

```text
(lldb) po tokenLines
▿ 1 element
  - 0 : <CTLine: 0x6000034b0000>{run count = 1, string range = (0, 1), width = 13, A/D/L = 12.72/4.08/0, glyph count = 1, runs = (

<CTRun: 0x7fe4fad6ffc0>{string range = (0, 1), string = "\u2026", attributes = {
    NSColor = "UIExtendedSRGBColorSpace 0.4 0.368627 1 1";
    NSFont = "<UICTFont: 0x7fe4fad2e020> font-family: \"PingFangSC-Regular\"; font-weight: normal; font-style: normal; font-size: 12.00pt";
    NSKern = 1;
    NSParagraphStyle = "Alignment 4, LineSpacing 1, ParagraphSpacing 0, ParagraphSpacingBefore 0, HeadIndent 0, TailIndent 0, FirstLineHeadIndent 0, LineHeight 0/0, LineHeightMultiple 0, LineBreakMode 0, Tabs (\n    28L,\n    56L,\n    84L,\n    112L,\n    140L,\n    168L,\n    196L,\n    224L,\n    252L,\n    280L,\n    308L,\n    336L\n), DefaultTabInterval 0, Blocks (\n), Lists (\n), BaseWritingDirection -1, HyphenationFactor 0, TighteningForTruncation NO, HeaderLevel 0";
}}

)
}
```

### PR DESCRIPTION
**Pull request by chansen22**
Band-aid for now
Fixes #40

### CODE REVIEW

File: Source/Classes/Drawing/Truncation.swift [hunk 1]
```diff
@@ -54,6 +54,8 @@ extension NantesLabel {
                 continue
             }
 
+            guard 0..<lines.count ~= originalIndex else { continue }
```
Comment (ngocholo) [inline Source/Classes/Drawing/Truncation.swift]: never seen this operator before, very swifty
